# Generated by Django 2.0.1 on 2018-01-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('applicants', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_init', models.CharField(blank=True, max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('NS', 'Not Submitted'), ('RV', 'Under Review'), ('MI', 'Missing Information'), ('AA', 'Applicant Accepted'), ('AD', 'Applicant Declined')], default='NS', max_length=2)),
                ('choice_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.Major')),
            ],
        ),
    ]
