# Generated by Django 2.0 on 2017-12-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Submitted'), ('RV', 'Under Review'), ('MI', 'Missing Information'), ('AA', 'Applicant Accepted'), ('AD', 'Applicant Declined')], default='NS', max_length=2),
        ),
    ]
