# Generated by Django 2.0.1 on 2018-01-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='shop_code',
            field=models.CharField(default='XX', max_length=2),
        ),
    ]
