# Generated by Django 2.0.1 on 2018-01-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_major_shop_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='choice_one',
        ),
        migrations.AddField(
            model_name='student',
            name='choices',
            field=models.ManyToManyField(to='enroll.Major'),
        ),
    ]
